<?php if (!isset($this->errorFlag) || $this->errorFlag === false): ?>
<fieldset>
    <input type="hidden" name="connection" value="submit" />
    <legend><?php echo $this->title ?></legend>
    <div>
        <?php if ($this->has('modelTitle')): ?>
            <label><?php echo $this->_('Knowledge Base') ?></label>
            <input type="text" class="text" value="<?php echo $this->modelTitle ?>" readonly="readonly" />
            <input type="hidden" name="modelUri" value="<?php echo $this->modelUri ?>" />
        <?php else: ?>
            <label for="model-input"><?php echo $this->_('Knowledge Base URI') ?></label>
            <?php if (!empty($this->modelUri)): ?>
                <?php // if model URI is set, don't allow it to be changed ?>
                <input type="text" class="text" id="model-input" name="modelUri" value="<?php echo $this->modelUri ?>" readonly="readonly" />
            <?php else: ?>
                <input type="text" class="text" id="model-input" name="modelUri" />
            <?php endif; ?>
            <br class="clearall" />
        <?php endif; ?>
		
		<label>Server (IP)</label>
        <input type="text" class="text" id="ip-input" name="ip" value="localhost"/>
		<br class="clearall" />
		<label>User</label>
        <input type="text" class="text" id="user-input" name="user" value="root"/>
		<br class="clearall" />
		<label>Password</label>
        <input type="password" class="text" id="password-input" name="password"/>

    </div>

    <!-- file upload -->
    <fieldset class="activeForm" id="connection">
        <div>	
			<label class="checkboxradio">(Statistical data using DataCube mapping)</label>
			<br class="clearall" />
			<label>Database</label>
	        <input type="text" class="text" id="database-input" name="database"/>
        </div>
    </fieldset>
</fieldset>
<?php endif; ?>
